version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: lab
      POSTGRES_DB: lab
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  python:
    build: ./python
    volumes:
      - ./scripts:/usr/src/app
    depends_on:
      - postgres
